Numpy is a python library for numerical computing. It provides fast and memory efficient areas compared to python list. Numpy arrays store same type element and perform mathematical operation faster.

In [25]:
import numpy as np
import pandas as pd

ARRAY CREATION

In [4]:
a=np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [11]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.08170545, 0.71072539, 0.10966242, 0.15992681, 0.92757908])

In [18]:
np.random.randint(1,10,(3,2))

array([[8, 7],
       [1, 7],
       [8, 5]], dtype=int32)

In [5]:
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.size)
type(a)

1
(5,)
int64
5


numpy.ndarray

RESHAPING AND FLATNING

In [6]:
print(a.reshape(5,1))
print(a.reshape(1,5))


[[1]
 [2]
 [3]
 [4]
 [5]]
[[1 2 3 4 5]]


In [15]:
a.reshape(5,1)
a.flatten()
arr=np.random.randint(1,10,(3,3))


In [17]:
print(arr)
print(arr[0])
print(arr[0,1])
print(arr[1:3,0:2])

[[2 6 8]
 [4 4 5]
 [4 9 9]]
[2 6 8]
6
[[4 4]
 [4 9]]


In [22]:
print(np.sum(arr),
np.mean(arr),
np.std(arr), #std deviation
np.var(arr), #variance
np.min(arr),
np.max(arr))


51 5.666666666666667 2.357022603955158 5.5555555555555545 2 9


AXIS CONCEPT

In [23]:
print(arr)

[[2 6 8]
 [4 4 5]
 [4 9 9]]


In [ ]:
print(arr.sum(axis=0)) #column u-down
print(arr.sum(axis=1)) #row r-left


print(arr.mean(axis=0))
print(arr.mean(axis=1))


print(arr.std(axis=0))
print(arr.std(axis=1))


print(arr.var(axis=0))
print(arr.var(axis=1))


print(arr.min(axis=0))
print(arr.min(axis=1))


print(arr.max(axis=0))
print(arr.max(axis=1))

[10 19 22]
[16 13 22]
[3.33333333 6.33333333 7.33333333]
[5.33333333 4.33333333 7.33333333]
[0.94280904 2.05480467 1.69967317]
[2.49443826 0.47140452 2.3570226 ]
[0.88888889 4.22222222 2.88888889]
[6.22222222 0.22222222 5.55555556]
[2 4 5]
[2 4 4]
[4 9 9]
[8 5 9]
