Numpy is a python library for numerical computing. It provides fast and memory efficient areas compared to python list. Numpy arrays store same type element and perform mathematical operation faster.

In [1]:
import numpy as np

ARRAY CREATION

In [6]:
a=np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [11]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])