Numpy is a python library for numerical computing. It provides fast and memory efficient areas compared to python list. Numpy arrays store same type element and perform mathematical operation faster.

In [3]:
import numpy as np

ARRAY CREATION

In [4]:
a=np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [11]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.08170545, 0.71072539, 0.10966242, 0.15992681, 0.92757908])

In [18]:
np.random.randint(1,10,(3,2))

array([[8, 7],
       [1, 7],
       [8, 5]], dtype=int32)

In [5]:
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.size)
type(a)

1
(5,)
int64
5


numpy.ndarray

RESHAPING AND FLATNING

In [6]:
print(a.reshape(5,1))
print(a.reshape(1,5))


[[1]
 [2]
 [3]
 [4]
 [5]]
[[1 2 3 4 5]]


In [ ]:
a.reshape(5,1)
a.flatten()


[1 2 3 4 5]


array([1, 2, 3, 4, 5])